USE [master]
GO
/****** Object:  Database [TaskManagmentApp]    Script Date: 11/25/2024 12:16:50 PM ******/
CREATE DATABASE [TaskManagmentApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskManagmentApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaskManagmentApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskManagmentApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TaskManagmentApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TaskManagmentApp] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskManagmentApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TaskManagmentApp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaskManagmentApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaskManagmentApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TaskManagmentApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaskManagmentApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TaskManagmentApp] SET  MULTI_USER 
GO
ALTER DATABASE [TaskManagmentApp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TaskManagmentApp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TaskManagmentApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TaskManagmentApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TaskManagmentApp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TaskManagmentApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TaskManagmentApp] SET QUERY_STORE = OFF
GO
USE [TaskManagmentApp]
GO
/****** Object:  Table [dbo].[TASKs]    Script Date: 11/25/2024 12:16:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TASKs](
	[task_id] [int] NOT NULL,
	[task_title] [nvarchar](20) NULL,
	[task_desc] [nvarchar](30) NULL,
	[task_status] [nvarchar](20) NULL,
	[task_date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[task_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Taskss]    Script Date: 11/25/2024 12:16:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Taskss](
	[task_id] [int] NOT NULL,
	[task_title] [nvarchar](20) NULL,
	[task_desc] [nvarchar](30) NULL,
	[task_status] [nvarchar](20) NULL,
	[task_date] [date] NULL,
	[Emp_name] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[task_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERr]    Script Date: 11/25/2024 12:16:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERr](
	[userr_id] [int] NOT NULL,
	[userr_name] [nvarchar](20) NULL,
	[userr_password] [nvarchar](20) NULL,
	[userr_email] [nvarchar](20) NULL,
	[userr_role] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[userr_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TaskManagmentApp] SET  READ_WRITE 
GO
